theme: jekyll-theme-minimal
title: Web Apps Conception
name: Rudy TUANI
description: Site web officiel du projet Web Apps Conception
url: https://webapps-conception.github.io
repository: webapps-conception/webapps-conception.github.io
show_downloads: false
google_analytics: G-JYQX8B02PN
plugins:
  - jekyll-sitemap
