theme: jekyll-theme-leap-day
title: Web Apps Conception
description: Site web officiel du projet Web Apps Conception
plugins:
  - jekyll-target-blank

target-blank:
    css_class: ext-link
    add_css_classes: css-class-one css-class-two
    noopener: false
    noreferrer: false
    rel: nofollow

