theme: jekyll-theme-leap-day
title: Blog Web Apps Conception
name: Rudy TUANI
email: rudy.t54230@gmail.com
description: Blog officiel du projet Web Apps Conception
baseurl: "/"
url: https://webapps-conception.github.io
repository: webapps-conception/webapps-conception.github.io
show_downloads: false
google_analytics: G-JYQX8B02PN
plugins:
  - jekyll-sitemap
  - _plugins/tag_generator.rb
